### ISSUE TITLE
EPEL module nginx:mainline now provides nginx version 1.21 

### ISSUE THREAD

**Issue by lhmathies-ufst** [jfut/nginx-module-auth-pam-rpm#2]
But the current nginx-module-auth-pam-1.5.3-1.module_el8.mainline.x86_64.rpm depends on version 1.19.

I'm using nginx:1.18 from AppStream instead.

(Both EPEL and AppStream have nginx:1.20 versions, might be nice to package the PAM module for that as well).

**Comment by jfut** [comment]
Thanks for the interesting information. I will build and release it for the new version.

**Comment by jfut** [comment]
@lhmathies-ufst I have released a new package, which now supports both centos:8:appstream:1.20 and centos:8:epel-modular:1.20!

https://github.com/jfut/nginx-module-auth-pam-rpm/releases/tag/v1.5.3-2

**Comment by lhmathies-ufst** [comment]
Lovely, thanks a lot!
