### ISSUE TITLE
Needs additional file

### ISSUE THREAD

**Issue by bgstack15** [jfut/nginx-module-auth-pam-rpm#7]
It might be obvious for Nginx wizards, but I needed to add this file:

`/usr/share/nginx/modules/mod-auth-pam.conf`:

```
load_module "/usr/lib64/nginx/modules/ngx_http_auth_pam_module.so";
```
If this were included in the rpm it would be even more of a turnkey solution.

**Comment by jfut** [comment]
Thanks for the report.

I checked other nginx-mod-*.rpm provided by the distribution, and they contain similar configuration files under /usr/share/nginx/modules/ by default, so I would add a similar configuration file that defaults to load_module.

**Comment by jfut** [comment]
I would rename the default configuration file `mod-auth-pam.conf` to `mod-http-auth-pam.conf` to follow the other modules in the distribution.
